spring.application.name=resume-ai

spring.datasource.url=jdbc:postgresql://localhost:5432/resume_ai_db
spring.datasource.username=postgres
spring.datasource.password=Yash#6601

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret=THIS_IS_MY_SUPER_SECRET_KEY_FOR_RESUME_AI_PROJECT_2026
app.jwt.expiration-ms=86400000